namespace SputnikAsm.LAssembler.LEnums
{
    public enum AParam
    {
        None,
        N1,
        N3,
        Al,
        Ax,
        Eax,
        Cl,
        Dx,
        Cs,
        Ds,
        Es,
        Ss,
        Fs,
        Gs,
        //regs
        R8,
        R16,
        R32,
        R64, //just for a few occasions
        Mm,
        Xmm,
        Ymm,
        St,
        St0,
        SReg,
        Cr,
        Dr,
        //memorylocs
        M8,
        M16,
        M32,
        M64,
        M80,
        M128,
        M256,
        Moffs8,
        Moffs16,
        Moffs32,
        //regs+memorylocs
        Rm8,
        Rm16,
        Rm32,
        R32M8,
        R32M16,
        Mmm32,
        Mmm64,
        Xmm8,
        Xmm16,
        Xmm32,
        Xmm64,
        Xmm128,
        Ymm256,
        //values
        Imm8,
        Imm16,
        Imm32,
        //relatives
        Rel8,
        Rel16,
        Rel32
    }
}
